name = "test-temp-2"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "test-temp-2_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "test-temp-2.wasm"
command = "npm run build:release"
